import  RPi.GPIO as GPIO
import time
GPIO.setmode(GPIO.BCM)
GPIO.setup(21, GPIO.OUT)
GPIO.setup(12, GPIO.OUT)
GPIO.setup(16, GPIO.OUT)
GPIO.output(21, GPIO.HIGH)
GPIO.output(16, GPIO.HIGH)
GPIO.output(12, GPIO.HIGH)
time.sleep(5)
GPIO.output(12, GPIO.LOW)
GPIO.output(16, GPIO.LOW)
GPIO.output(21, GPIO.LOW)
time.sleep(0.2)
GPIO.output(21, GPIO.HIGH)
GPIO.output(16, GPIO.HIGH)
GPIO.output(12, GPIO.HIGH)
time.sleep(0.2)
GPIO.output(12, GPIO.LOW)
GPIO.output(16, GPIO.LOW)
GPIO.output(21, GPIO.LOW)
